name: music_atlas
description: A music theory and fretboard exploration app.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Fonts
  google_fonts: ^6.3.3

  # UI & Animations
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  shimmer: ^3.0.0
  blur: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/images/




